<?php

/**
 * @file
 * Redhen Organizations main module
 *
 */


/**
 * Implements hook_entity_info().
 */
function redhen_org_entity_info() {
  return array(
    'redhen_org' => array(
      'label' => t('Organization'),
      'plural label' => t('Organizations'),
      'controller class' => 'EntityAPIController',
      'metadata controller class' => 'RedhenOrgMetadataController',
      'entity class' => 'RedhenOrg',
      'base table' => 'redhen_org',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'org_id',
        'bundle' => 'type',
      ),
      'bundle keys' => array(
        'bundle' => 'name',
      ),
      'bundles' => array(),
      'view modes' => array(
        'full' => array(
          'label' => t('Full organization'),
          'custom settings' => FALSE,
        ),
      ),
      'uri callback' => 'entity_class_uri',
      'token type' => 'redhen_org',
      'module' => 'redhen_org',
      'label callback' => 'entity_class_label'
    ),
    'redhen_org_type' => array(
      'label' => t('Organization type'),
      'entity class' => 'RedhenOrgType',
      'controller class' => 'EntityAPIControllerExportable',
      'base table' => 'redhen_org_type',
      'fieldable' => FALSE,
      'bundle of' => 'redhen_org',
      'exportable' => TRUE,
      'token type' => 'redhen_org_type',
      'entity keys' => array(
        'id' => 'org_type_id',
        'name' => 'name',
        'label' => 'label',
      ),
      'access callback' => 'redhen_org_type_access',
      'module' => 'redhen_org',
      // Enable the entity API's admin UI.
      'admin ui' => array(
        'path' => 'admin/structure/redhen/org_types',
        'file' => 'redhen_org_type.admin.inc',
        'file path' => drupal_get_path('module', 'redhen_org') . '/includes',
        'controller class' => 'RedhenOrgTypeUIController',
      ),
    ),
  );
}

/**
 * Implements hook_entity_info_alter().
 *
 * We are adding the info about the organization types via a hook to avoid a recursion
 * issue as loading the model types requires the entity info as well.
 */
function redhen_org_entity_info_alter(&$entity_info) {
  foreach (redhen_org_get_types() as $type => $info) {
    $entity_info['redhen_org']['bundles'][$type] = array(
      'label' => $info->label,
      'admin' => array(
        'path' => 'admin/structure/redhen/org_types/manage/%redhen_org_type',
        'real path' => 'admin/structure/redhen/org_types/manage/' . $type,
        'bundle argument' => 5,
        'access arguments' => array('administer redhen_org types'),
      ),
    );
  }
}

/**
 * Implements hook_menu().
 */
function redhen_org_menu() {
  $items = array();

  // Add a org.
  $items['redhen/org'] = array(
    'title' => 'Organizations',
    'description' => 'View RedHen CRM Organizations.',
    'page callback' => 'redhen_org_page',
    'file' => 'includes/redhen_org.pages.inc',
    'access arguments' => array('view orgs'),
  );

  // Add a org.
  $items['redhen/org/add'] = array(
    'title' => 'Add an organization',
    'description' => 'Add a new organization.',
    'page callback' => 'redhen_org_types_list_page',
    'access callback' => 'redhen_org_access',
    'access arguments' => array('create'),
    'file' => 'includes/redhen_org.pages.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $entity_info = entity_get_info('redhen_org');
  foreach($entity_info['bundles'] as $key => $bundle) {
    $type_url_str = str_replace('_', '-', $key);
    $items['redhen/org/add/' . $type_url_str] = array(
      'title' => $bundle['label'],
      'title callback' => 'check_plain',
      'description' => isset($bundle['description']) ? $bundle['description'] : '',
      'page callback' => 'redhen_org_add_page',
      'page arguments' => array($key),
      'access callback' => 'redhen_org_access',
      'access arguments' => array('create'),
      'file' => 'includes/redhen_org.pages.inc',
    );
  }

  $items['redhen/org/%redhen_org'] = array(
    'title callback' => 'redhen_org_org_title',
    'title arguments' => array(2),
    'page callback' => 'redhen_org_view',
    'page arguments' => array(2),
    'access callback' => 'redhen_org_access',
    'access arguments' => array('view', 2),
    'weight' => 10,
  );
  $items['redhen/org/%redhen_org/view'] = array(
    'title' => 'Summary',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  $items['redhen/org/%redhen_org/view/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('redhen_org_org_delete_form', 2),
    'access callback' => 'redhen_org_access',
    'access arguments' => array('delete', 2),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'file' => 'includes/redhen_org.forms.inc',
  );
  $items['redhen/org/%redhen_org/view/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('redhen_org_org_form', 2),
    'access callback' => 'redhen_org_access',
    'access arguments' => array('edit', 2),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/redhen_org.forms.inc',
  );

  $items['redhen/org/%redhen_org/archive'] = array(
    'title' => 'Archive',
    'page callback' => 'redhen_org_archive',
    'page arguments' => array(2),
    'access callback' => 'redhen_org_access',
    'access arguments' => array('edit', 2),
    'type' => MENU_CALLBACK,
  );

  $items['redhen/org/%redhen_org/primary/%redhen_contact'] = array(
    'title callback' => 'Change primary contact',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('redhen_org_set_primary_form', 2, 4),
    'access callback' => 'redhen_org_access',
    'access arguments' => array('edit', 2),
    'type' => MENU_CALLBACK,
    'file' => 'includes/redhen_org.forms.inc',
  );

  // path with autocomplete function for cities
  $items['redhen/org/autocomplete'] = array(
    'title' => 'Autocomplete for RedHen Organizations',
    'page callback' => '_redhen_org_autocomplete',
    'access callback' => 'redhen_org_access',
    'access arguments' => array('edit'),  //or whatever permission makes sense
    'type' => MENU_CALLBACK,
    'file' => 'includes/redhen_org.pages.inc',
  );

  if (module_exists('devel')) {
    $items['redhen/org/%redhen_org/devel'] = array(
      'title' => 'Devel',
      'page callback' => 'redhen_devel_load_object',
      'page arguments' => array('redhen_org', 2),
      'access arguments' => array('access devel information'),
      'type' => MENU_LOCAL_TASK,
      'weight' => 100,
    );
    $items['redhen/org/%redhen_org/devel/load'] = array(
      'title' => 'Load',
      'type' => MENU_DEFAULT_LOCAL_TASK,
    );
    $items['redhen/org/%redhen_org/devel/render'] = array(
      'title' => 'Render',
      'page callback' => 'redhen_devel_render_object',
      'page arguments' => array('redhen_org', 2),
      'access arguments' => array('access devel information'),
      'type' => MENU_LOCAL_TASK,
      'weight' => 100,
    );
  }

  return $items;
}

/**
 * Implements hook_theme().
 */
function redhen_org_theme() {
  return array(
    'redhen_org_add_list' => array(
      'variables' => array('content' => NULL),
      'file' => 'includes/redhen_org.forms.inc',
    ),
    'redhen_org_list' => array(
      'variables' => array('orgs' => NULL, 'header' => NULL),
    )
  );
}

/**
 * Loads an org by ID.
 */
function redhen_org_load($org_id) {
  if (empty($org_id)) {
    return FALSE;
  }

  $orgs = redhen_org_load_multiple(array($org_id), array());
  return $orgs ? reset($orgs) : FALSE;
}

/**
 * Loads multiple orgs by ID or based on a set of matching conditions.
 *
 * @see entity_load()
 *
 * @param $org_ids
 *   An array of org IDs.
 * @param $conditions
 *   An array of conditions on the {redhen_org} table in the form
 *     'field' => $value.
 * @param $reset
 *   Whether to reset the internal org loading cache.
 *
 * @return
 *   An array of org objects indexed by org_id.
 */
function redhen_org_load_multiple($org_ids = array(), $conditions = array(), $reset = FALSE) {
  if (empty($org_ids) && empty($conditions)) {
    return array();
  }

  return entity_load('redhen_org', $org_ids, $conditions, $reset);
}

/**
 * Archive an org.
 *
 * @param $org
 *   The full org object to save.
 *
 * @return
 *   The saved org object.
 */
function redhen_org_archive($org) {
  // flip the state and save
  $org->redhen_state = !$org->redhen_state;
  drupal_set_message(t('@org has been updated.', array('@org' => $org->label())), 'status');
  $org->save();
  drupal_goto(drupal_get_destination());
}

/**
 * Checks org access for various operations.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create' or
 *   'delete'.
 * @param $org
 *   Optionally a org to check access for or for the create operation the
 *   org type. If nothing is given access permissions for all orgs are returned.
 * @param $account
 *   The user to check for. Leave it to NULL to check for the current user.
 */
function redhen_org_access($op, $org = NULL, $account = NULL) {
  global $user;
  $account = isset($account) ? $account : $user;

  if (user_access('administer orgs', $account)) {
    return TRUE;
  }

  if ($op == 'view' && user_access('access orgs', $account)) {
    return TRUE;
  }

  if (isset($org) && is_string($org) && $op == 'create' && user_access('create ' . $org . ' orgs', $account)) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Display a org.
 *
 * @param  $org
 *   A Fully loaded org object.
 * @return void
 */
function redhen_org_view(RedhenOrg $org) {
  return $org->view();
}

/**
 * Title callback for hook_menu().
 *
 * @param  $org
 *   A loaded org object.
 * @return void
 */
function redhen_org_org_title(RedhenOrg $org) {
  return $org->label();
}

/**
 * Implements hook_field_extra_fields().
 */
function redhen_org_field_extra_fields() {
  $extra = array();

  foreach (redhen_org_get_types() as $type => $org_type) {
    $extra['redhen_org'][$type] = array(
      'form' => array(
        'name' => array(
          'label' => t('Organization name'),
          'description' => t('Organization name'),
          'weight' => 0,
        ),
        'redhen_state' => array(
          'label' => t('State'),
          'description' => t('Organization state'),
          'weight' => 0,
        ),
      ),
      'display' => array(
        'name' => array(
          'label' => t('Name'),
          'description' => t('Organization name.'),
          'weight' => 0,
        ),
        'redhen_state' => array(
          'label' => t('State'),
          'description' => t('Organization state'),
          'weight' => 0,
        ),
      ),
    );
  }

  return $extra;
}

/**
 * Gets an array of all org types, keyed by the name.
 *
 * @param $name
 *   If set, the type with the given name is returned.
 */
function redhen_org_get_types($name = NULL) {
  $types = entity_load_multiple_by_name('redhen_org_type', isset($name) ? array($name) : FALSE);
  return isset($name) ? reset($types) : $types;
}

/**
 * Access callback for the entity API.
 */
function redhen_org_type_access($op, $type = NULL, $account = NULL) {
  return user_access('administer redhen_org types', $account);
}

/**
 * Menu argument loader; Load an organization type by string.
 *
 * @param $type
 *   The machine-readable name of an organization type to load.
 * @return
 *   An organization type array or FALSE if $type does not exist.
 */
function redhen_org_type_load($type) {
  return redhen_org_get_types($type);
}

/**
 * Saves a model type to the db.
 */
function redhen_org_type_save(RedhenOrgType $type) {
  $type->save();
}

/**
 * Deletes a model type from the db.
 */
function redhen_org_type_delete(RedhenOrgType $type) {
  $type->delete();
}

/**
 * Returns HTML for a list of available org types for org creation.
 *
 * @param $variables
 *   An associative array containing:
 *   - content: An array of content types.
 *
 * @ingroup themeable
 */
function theme_redhen_org_add_list($variables) {
  $content = $variables['content'];
  $output = '';

  if ($content) {
    $output = '<dl class="node-type-list">';
    foreach ($content as $item) {
      $output .= '<dt>' . l($item['title'], $item['href'], $item['localized_options']) . '</dt>';
      $output .= '<dd>' . filter_xss_admin($item['description']) . '</dd>';
    }
    $output .= '</dl>';
  }
  else {
    $output = '<p>' . t('You have not created any organization types yet. Go to the <a href="@create-org-types">organization type creation page</a> to add a new content type.', array('@create-org-types' => url('admin/structure/redhen/org-types'))) . '</p>';
  }
  return $output;
}

/**
 * Theme function for organization list.
 *
 * @param $variables
 * @return string
 */
function theme_redhen_org_list($variables) {
  $orgs = $variables['orgs'];
  $header = $variables['header'];
  if (!empty($orgs)) {
    $rows = array();
    foreach($orgs as $org) {
      $archive = $org->redhen_state == REDHEN_STATE_ACTIVE ? t('archive') : t('restore');
      $actions = array(
        l(t('view'), 'redhen/org/' . $org->org_id),
        l(t('edit'), 'redhen/org/' . $org->org_id . '/view/edit', array('query' => drupal_get_destination())),
        l($archive, 'redhen/org/' . $org->org_id . '/archive', array('query' => drupal_get_destination())),
        l(t('delete'), 'redhen/org/' . $org->org_id . '/view/delete', array('query' => drupal_get_destination())),
      );

      $redhen_org_type = redhen_org_type_load($org->type);

      $data = array(
        $org->label,
        $redhen_org_type->label,
        format_date($org->updated),
        $org->redhen_state == REDHEN_STATE_ACTIVE ? t('active') : t('archived'),
        implode(' | ', $actions)
      );

      $row_classes = array();
      // Set a class for the row depending on if the membership is active or archived
      $row_classes[] = $org->redhen_state == REDHEN_STATE_ACTIVE ? 'active' : 'archived';

      $rows[] = array(
        'data' => $data,
        'class' => $row_classes,
      );
    }
    $render['table'] = array(
      '#theme' => 'table',
      '#header' => $header,
      '#rows' => $rows
    );
    $render['pager'] = array(
      '#theme' => 'pager'
    );
  }
  else {
    // no results, set a message
    $render['no-result'] = array(
      '#type' => 'markup',
      '#markup' => t('Sorry, there are no organizations that match your criteria.'),
    );
  }

  return render($render);
}
