<?php

/**
 * @file
 * Defines basic functionality common to all parts of the Redhen CRM.
 */

// Definitions
define('REDHEN_STATUS_ACTIVE', 1);
define('REDHEN_STATUS_ARCHIVED', 0);

function redhen_menu() {
  $items = array();

  // Menu items that are basically just menu blocks.
  $items['redhen'] = array(
    'title' => 'RedHen CRM',
    'description' => 'RedHen CRM home',
    'weight' => -8,
    'page callback' => 'redhen_admin_menu_block_page',
    'menu_name' => 'navigation',
    'access arguments' => array('access administration pages'),
    'file' => 'redhen.admin.inc',
  );
  $items['admin/structure/redhen'] = array(
    'title' => 'RedHen CRM',
    'description' => 'Administer RedHen CRM items, such as contact, group types, etc.',
    'weight' => -8,
    'page callback' => 'redhen_admin_menu_block_page',
    'menu_name' => 'navigation',
    'access arguments' => array('access administration pages'),
    'file' => 'redhen.admin.inc',
    'menu_name' => 'management',
  );

  return $items;
}

/**
 * Wrapper for devel_load_object which is in an include file.
 */
function redhen_devel_load_object($type, $object, $name = NULL) {
  if (module_exists('devel')) {
    module_load_include('inc', 'devel', 'devel.pages');
    return devel_load_object($type, $object, $name);
  }
}

/**
 * Wrapper function for devel_render_object which is in an include file.
 */
function redhen_devel_render_object($type, $object, $name = NULL) {
  if (module_exists('devel')) {
    module_load_include('inc', 'devel', 'devel.pages');
    return devel_render_object($type, $object, $name);
  }
}

/**
 * Implements hook_theme().
 */
function redhen_theme() {
  return array(
    'redhen_property_field' => array(
      'variables' => array(
        'label_hidden' => FALSE,
        'title_attributes' => NULL,
        'label' => '',
        'content_attributes' => NULL,
        'items' => array(),
        'item_attributes' => array(array()),
        'classes' => '',
        'attributes' => '',
      )
    ),
  );
}

/**
 * Theme function for redhen properties. Simple wrapper around theme_field
 * that sets default values and ensures proeprties render consistently with
 * fields.
 */
function theme_redhen_property_field($variables) {
  return theme_field($variables);
}
