<?php

/**
 * @file
 * Defines email, phone and address field types for RedHen CRM.
 */


/**
 * Implements hook_field_info().
 */
function redhen_fields_field_info() {
  return array(
    'redhen_email' => array(
      'label' => t('RedHen Email'),
      'description' => t("This field allows you to store multiple email values with labels "),
      'settings' => array('labels' => array()),
      'default_widget' => 'redhen_email_widget',
      'default_formatter' => 'redhen_email_formatter',
    ),
  );
}

/**
 * Implements hook_field_settings_form().
 */
function redhen_fields_field_settings_form($field, $instance, $has_data) {
  $settings = $field['settings'];

  $form = array();
  if ($field['type'] == 'redhen_email') {
    $form['labels'] = array(
      '#type' => 'textarea',
      '#rows' => 10,
      '#title' => t('Labels'),
      '#default_value' => redhen_fields_allowed_labels_string($settings['labels']),
      '#required' => TRUE,
      '#description' => t('The possible labels for values in this field. Enter one value per line, in the format key|label. Key must be an integer.'),
      '#element_validate' => array('redhen_fields_allowed_labels_setting_validate'),
      '#field_has_data' => $has_data,
      '#field' => $field,
    );
  }

  return $form;
}

/**
 * Generates a string representation of an array of 'labels'.
 *
 * This string format is suitable for edition in a textarea.
 *
 * @param $values
 *   An array of values, where array keys are values and array values are
 *   labels.
 *
 * @return
 *   The string representation of the $values array:
 *    - Values are separated by a carriage return.
 *    - Each value is in the format "value|label" or "value".
 */
function redhen_fields_allowed_labels_string($values) {
  $lines = array();
  foreach ($values as $key => $value) {
    $lines[] = "$key|$value";
  }
  return implode("\n", $lines);
}

/**
 * Element validate callback; check that the entered values are valid.
 */
function redhen_fields_allowed_labels_setting_validate($element, &$form_state) {
  $field = $element['#field'];
  $has_data = $element['#field_has_data'];
  $generate_keys = !$has_data;

  $values = redhen_fields_extract_allowed_labels($element['#value'], $generate_keys);

  if (!is_array($values)) {
    form_error($element, t('Allowed labels list: invalid input.'));
  }
  else {
    // Check that keys are valid for the field type.
    foreach ($values as $key => $value) {
      if (!preg_match('/^-?\d+$/', $key)) {
        form_error($element, t('Allowed labels list: keys must be integers.'));
        break;
      }
    }

    // Prevent removing values currently in use.
    if ($has_data) {
      $lost_keys = array_diff(array_keys($field['settings']['labels']), array_keys($values));
      if (_redhen_fields_labels_in_use($field, $lost_keys)) {
        form_error($element, t('Allowed labels list: some labels are being removed while currently in use.'));
      }
    }

    form_set_value($element, $values, $form_state);
  }
}

/**
 * Parses a string of 'allowed labels' into an array.
 *
 * @param $string
 *   The list of allowed labels in string format descibed in
 *   redhen_fields_allowed_labels_string().
 * @param $generate_keys
 *   Boolean value indicating whether to generate keys based on the position of
 *   the value if a key is not manually specified, and if the value cannot be
 *   used as a key.
 *
 * @return
 *   The array of extracted key/value pairs, or NULL if the string is invalid.
 *
 * @see redhen_fields_allowed_labels_string()
 */
function redhen_fields_extract_allowed_labels($string, $generate_keys) {
  $values = array();

  $list = explode("\n", $string);
  $list = array_map('trim', $list);
  $list = array_filter($list, 'strlen');

  $generated_keys = $explicit_keys = FALSE;
  foreach ($list as $position => $text) {
    $value = $key = FALSE;

    // Check for an explicit key.
    $matches = array();
    if (preg_match('/(.*)\|(.*)/', $text, $matches)) {
      $key = $matches[1];
      $value = $matches[2];
      $explicit_keys = TRUE;
    }
    // Otherwise see if we can use the value as the key. Detecting true integer
    // strings takes a little trick.
    elseif ((is_numeric($text) && (float) $text == intval($text))) {
      $key = $value = $text;
      $explicit_keys = TRUE;
    }
    // Otherwise see if we can generate a key from the position.
    elseif ($generate_keys) {
      $key = (string) $position;
      $value = $text;
      $generated_keys = TRUE;
    }
    else {
      return;
    }
    $values[$key] = $value;
  }

  // We generate keys only if the list contains no explicit key at all.
  if ($explicit_keys && $generated_keys) {
    return;
  }

  return $values;
}

/**
 * Checks if a list of values are being used in actual field values.
 */
function _redhen_fields_labels_in_use($field, $values) {
  if ($values) {
    $query = new EntityFieldQuery();
    $found = $query
      ->fieldCondition($field['field_name'], 'label_id', $values)
      ->range(0, 1)
      ->execute();
    return !empty($found);
  }

  return FALSE;
}

/**
 * Implements hook_field_instance_settings_form().
 */
function redhen_fields_field_instance_settings_form($field, $instance) {
  $settings = $instance['settings'];

  $form = array();

  return $form;
}

/**
 * Implements hook_field_validate().
 */
function redhen_fields_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  switch ($field['type']) {
    case 'redhen_email':
      foreach ($items as $delta => $item) {
        if (!empty($item['value'])) {
          if (filter_var($item['value'], FILTER_VALIDATE_EMAIL) === FALSE) {
            $errors[$field['field_name']][$langcode][$delta][] = array(
              'error' => 'redhen_fields_invalid_email',
              'message' => t('%name: Not a valid email address.', array('%name' => t($instance['label']))),
              'delta' => $delta,
            );
          }
          if (_redhen_fields_email_in_use($field, $entity_type, $entity, $item['value'])) {
            $errors[$field['field_name']][$langcode][$delta][] = array(
              'error' => 'redhen_fields_invalid_email',
              'message' => t('%name: Email address already in use.', array('%name' => t($instance['label']))),
              'delta' => $delta,
            );
          }
        }
      }
      break;
  }
}

function _redhen_fields_email_in_use($field, $entity_type, $entity, $value) {
  if ($value) {
    $entity_info = entity_get_info($entity_type);
    $query = new EntityFieldQuery();
    $found = $query
      ->entityCondition('entity_type', $entity_type, '=')
      ->entityCondition('entity_id', $entity->{$entity_info['entity keys']['id']}, '!=')
      ->fieldCondition($field['field_name'], 'value', $value)
      ->range(0, 1)
      ->execute();
    return !empty($found);
  }

  return FALSE;
}

/**
 * Implements hook_field_load().
 *
 * Where possible, generate the sanitized version of each field early so that
 * it is cached in the field cache. This avoids looking up from the filter cache
 * separately.
 *
 * @see text_field_formatter_view()
 */
function redhen_fields_field_load($entity_type, $entities, $field, $instances, $langcode, &$items) {
  foreach ($entities as $id => $entity) {
    foreach ($items[$id] as $delta => $item) {
      $items[$id][$delta]['label'] = $field['settings']['labels'][$item['label_id']];
    }
  }
}

/**
 * Implements hook_field_is_empty().
 */
function redhen_fields_field_is_empty($item, $field) {
  return (!isset($item['value']) || $item['value'] === '');
}

/**
 * Implements hook_field_formatter_info().
 */
function redhen_fields_field_formatter_info() {
  return array(
    'redhen_email_formatter' => array(
      'label' => t('Default'),
      'field types' => array('redhen_email'),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function redhen_fields_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $element = array();

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function redhen_fields_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $summary = '';

  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function redhen_fields_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
    case 'redhen_email_formatter':

      break;
  }

  return $element;
}

/**
 * Implements hook_theme().
 */
function redhen_fields_theme($existing, $type, $theme, $path) {
  return array(
    'redhen_email_widget' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Implements hook_field_widget_info().
 */
function redhen_fields_field_widget_info() {
  return array(
    'redhen_email_widget' => array(
      'label' => t('Email field'),
      'field types' => array('redhen_email'),
      'settings' => array(),
      'behaviors' => array(
        'multiple values' => FIELD_BEHAVIOR_CUSTOM,
        'default value' => FIELD_BEHAVIOR_NONE,
      ),
    ),
  );
}

/**
 * Implements hook_field_widget_settings_form().
 */
function redhen_fields_field_widget_settings_form($field, $instance) {
  $widget = $instance['widget'];
  $settings = $widget['settings'];

  $form = array();

  return $form;
}

/**
 * Implements hook_field_widget_form().
 */
function redhen_fields_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $orig_element = $element;
  $count =  ($field['cardinality'] == -1) ? 50 : $field['cardinality'];

  for ($i = 0; $i < $count; $i++) {
    if (isset($items[$i]['default']) && $items[$i]['default'] == 1) {
      $default_element = $i;
    }

    switch ($instance['widget']['type']) {
      case 'redhen_email_widget':
        $orig_element['#title_display'] = 'invisible';
        $email = $label = $bulk = $hold = $orig_element;

        // Set the email field
        $email['#type'] = 'textfield';
        $email['#default_value'] = isset($items[$i]['value']) ? $items[$i]['value'] : NULL;
        $email['#size'] = 35;
        $email['#weight'] = -1;

        // Set the label field
        $label['#type'] = 'select';
        $label['#multiple'] = FALSE;
        $label['#options'] = $field['settings']['labels'];
        $label['#default_value'] = isset($items[$i]['label_id']) ? $items[$i]['label_id'] : NULL;
        $label['#weight'] = 1;

        // Set the hold field
        $hold['#type'] = 'checkbox';
        $hold['#default_value'] = isset($items[$i]['hold']) ? $items[$i]['hold'] : FALSE;
        $hold['#weight'] = 2;

        // Set the bulk field
        $bulk['#type'] = 'checkbox';
        $bulk['#default_value'] = isset($items[$i]['bulk']) ? $items[$i]['bulk'] : TRUE;
        $bulk['#weight'] = 3;

        // Assemble into a single element
        $element[$i]['value'] = $email;
        $element[$i]['label_id'] = $label;
        $element[$i]['hold'] = $hold;
        $element[$i]['bulk'] = $bulk;

        // Handle styling
        $element['#theme'] = 'redhen_email_widget';
        $element['#element_validate'] = array('redhen_fields_email_widget_validate');
        break;
    }
  }

  // Handle default radio button element

  $element['default'] = array(
    '#type' => 'radios',
    '#title' => 'default',
    '#options' => array_fill(0, $count, ''),
    '#default_value' => isset($default_element) ? $default_element : 0,
  );

  $element['#attached']['css'] = array(drupal_get_path('module', 'redhen_fields') . '/redhen_fields.css');
  $element['#attached']['js'] = array(drupal_get_path('module', 'redhen_fields') . '/redhen_fields.js');

  return $element;
}

/**
 * Implements hook_field_widget_error().
 */
function redhen_fields_field_widget_error($element, $error, $form, &$form_state) {
  switch ($error['error']) {
    case 'redhen_fields_invalid_email':
      $error_element = $element[$error['delta']]['value'];
      break;
    default:
      $error_element = $element[$element['#columns'][0]];
      break;
  }

  form_error($error_element, $error['message']);
}

/**
 * Theme the email widget.
 */
function theme_redhen_email_widget($vars) {
  $element = &$vars['element'];

  $add_another = '<a href="#" class="add-another">' . t('add email') . '</a>';

  $output = '<div class="field-label"><label>' . check_plain($element['#title']) . ' ' . $add_another . '</label></div>';
  $output .= '<div class="legend"><div class="email-label-section">' . t('Address') . '</div>';
  $output .= '<div class="bulk-label">' . t('Bulk mailings?') . '</div>';
  $output .= '<div class="hold-label">' . t('On hold?') . '</div>';
  $output .= '<div class="primary-label">' . t('Primary') . '</div></div>';
  foreach ($element as $key => $value) {
    if (is_numeric($key)) {
      $output .= "<div class=\"redhen-email-widget-item item-$key\">";
      $output .= '<div class="email-label-section">';
      $output .= render($value['value']);
      $output .= render($value['label_id']);
      $output .= '</div>';
      $output .= '<div class="bulk-label">' . render($value['bulk']) . '</div>';
      $output .= '<div class="hold-label">' . render($value['hold']) . '</div>';
      $output .= '<div class="primary-label">' . render($element['default'][$key]) . '</div>';
      $output .= '<a href="#" class="remove">' . t('remove') . '</a>';
      $output .= '</div>';
    }
  }

  return $output;
}

function redhen_fields_email_widget_validate($element, &$form_state) {
  $parents = $element['#parents'];
  $element_values = drupal_array_get_nested_value($form_state['values'], $parents);
  $default_item = $element_values['default'];
  drupal_array_set_nested_value($form_state['values'], array_merge($parents, array('default')), NULL);
  foreach ($element_values as $key => $item) {
    if (is_numeric($key)) {
      // Set the default value
      if ($key == $default_item) {
        drupal_array_set_nested_value($form_state['values'], array_merge($parents, array($key, 'default')), 1);
      }
      else {
        drupal_array_set_nested_value($form_state['values'], array_merge($parents, array($key, 'default')), 0);
      }

      // Clear out empty elements
      if (empty($item['value'])) {
        drupal_array_set_nested_value($form_state['values'], array_merge($parents, array($key)), NULL);
      }
    }
  }
}
