<?php

function redhen_relation_menu() {
  $items = array();

  $items['redhen/contact/%redhen_contact/connections'] = array(
    'title' => 'Connections',
    'page callback' => 'redhen_relation_connections_page',
    'page arguments' => array(2),
    'access callback' => 'redhen_contact_access',
    'access arguments' => array('view', 2),
    'type' => MENU_LOCAL_TASK,
  );

  $items['redhen/contact/%redhen_contact/connections/add'] = array(
    'title' => 'Add Connection',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('redhen_relation_connection_form', 2),
    'access callback' => 'redhen_contact_access',
    'access arguments' => array('edit', 2),
    'type' => MENU_LOCAL_ACTION,
  );

  return $items;
}

function redhen_relation_connections_page(RedhenContact $contact) {
//  $connections = relation_get_related_entity('redhen_contact', $contact->contact_id);

  $query = relation_query('redhen_contact', $contact->contact_id);
  $results = $query->execute();
  if ($results) {
    $relations = relation_load_multiple(array_keys($results));
    foreach($relations as $relation) {
      $rows[] = array($relation->relation_type);
    }
//    $entities = field_get_items('relation', $relation, 'endpoints');
  }

dpm($relations);

//  dpm($connections);
  $header = array('Type');
  return theme('table', array('header' => $header, 'rows' => $rows));
}

function redhen_relation_connection_form($form, &$form_state, RedhenContact $contact) {
  $form_state['contact'] = $contact;

  $relation_types = relation_get_available_types('redhen_contact', $contact->bundle());
  $options = array();
  foreach($relation_types as $type) {
    $options[$type->relation_type] = $type->label;
  }
  $form['type'] = array(
    '#title' => t('Connection type'),
    '#type' => 'select',
    '#options' => $options
  );

  $options = array();
  foreach(entity_load('redhen_org') as $org) {
    $options[$org->org_id] = $org->label;
  }
  $form['org'] = array(
    '#title' => t('Organization'),
    '#type' => 'select',
    '#options' => $options
  );

  field_attach_form('relation', reset($relation_types), $form, $form_state);

  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save connection'),
  );

  return $form;
}

function redhen_relation_connection_form_submit($form, &$form_state) {
  $contact = &$form_state['contact'];
  $values = $form_state['values'];
  $relation = relation_create($values['type'], array(
    array('entity_type' => 'redhen_contact', 'entity_id' => $contact->contact_id),
    array('entity_type' => 'redhen_org', 'entity_id' => $values['org']),
  ));

  relation_save($relation);
  field_attach_submit('relation', relation_type_load($values['type']), $form, $form_state);

  drupal_set_message(t('The connection has been saved.'));
  $form_state['redirect'] = "redhen/contact/{$contact->contact_id}/connections";
}
