<?php

define('REDHEN_ORG_GROUP_FIELD', 'field_redhen_org_group');

/**
 * Implements hook_form_FORM_ID_alter().
 */
function redhen_org_group_form_redhen_org_type_form_alter(&$form, &$form_state) {
  // add group specific settings
  $redhen_org_type = $form['#redhen_org_type'];
  $form['data']['group'] = array(
    '#type' => 'checkbox',
    '#title' => 'Groupify',
    '#default_value' => isset($redhen_org_type->group) ? $redhen_org_type->group : NULL
  );
  $form['data']['group_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Group settings'),
    '#states' => array(
      'visible' => array(
        ':input[name="data[group]"]' => array('checked' => TRUE),
      ),
    )
  );
  $form['data']['group_settings']['private'] = array(
    '#type' => 'checkbox',
    '#title' => t('Private'),
    '#default_value' => isset($redhen_org_type->group_settings['private']) ? $redhen_org_type->group_settings['private'] : NULL
  );

  $form['data']['group_settings']['content_types'] = array(
    '#type' => 'select',
    '#title' => t('Content types'),
    '#description' => t('Select which content types can be posted into this group.'),
    '#options' => node_type_get_names(),
    '#multiple' => TRUE,
    '#default_value' => isset($redhen_org_type->group_settings['content_types']) ? $redhen_org_type->group_settings['content_types'] : array()
  );

  $form['#submit'][] = 'redhen_org_group_redhen_org_type_form_submit';
}

/**
 * Submit handler for redhen_org_type_form().
 *
 * @param $form
 * @param $form_state
 */
function redhen_org_group_redhen_org_type_form_submit($form, &$form_state) {
  $content_types = $form_state['values']['data']['group_settings']['content_types'];

  // delete field instances if a content type was removed
  foreach ($form['data']['group_settings']['content_types']['#default_value'] as $old_type) {
    if (!isset($content_types[$old_type])) {
      $instance = field_read_instance('node', REDHEN_ORG_GROUP_FIELD, $old_type);
      if ($instance) {
        field_delete_instance($instance, FALSE);
        field_purge_batch(10);
        drupal_set_message(t('Field %label has been deleted from the %type content type.',
          array('%label' => $instance['label'], '%type' => $old_type)));
      }
    }
  }

  // create an instance of our audience field if it doesn't already exist
  foreach ($content_types as $type) {
    $instance = field_read_instance('node', REDHEN_ORG_GROUP_FIELD, $type);
    if (!$instance) {
      $instance = array(
        'field_name' => REDHEN_ORG_GROUP_FIELD,
        'entity_type' => 'node',
        'bundle' => $type,
        'label' => t('Group'),
        'widget' => array(
          'module' => 'options',
          'settings' => array(),
          'type' => 'options_select',
        ),
      );
      field_create_instance($instance);
      drupal_set_message(t('Field %label has been added to the %type content type.',
        array('%label' => $instance['label'], '%type' => $type)));
    }
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function redhen_org_group_ctools_plugin_directory($module, $plugin) {
  if ($module == 'entityreference') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_redhen_org_type_delete()
 *
 * @param RedhenOrgType $redhen_org_type
 */
function redhen_org_group_redhen_org_type_delete(RedhenOrgType $redhen_org_type) {
  // delete redhen group field if not used by another org type
  if (isset($redhen_org_type->group_settings['content_types'])) {
    $org_types = redhen_org_get_types();
    foreach ($redhen_org_type->group_settings['content_types'] as $type) {
      $in_use = FALSE;
      foreach ($org_types as $org_type) {
        if ($org_type->name != $redhen_org_type->name && isset($org_type->group) && $org_type->group) {
          if (isset($org_type->group_settings['content_types'])) {
            $in_use = in_array($type, $org_type->group_settings['content_types']);
          }
        }
      }

      if (!$in_use) {
        $instance = field_read_instance('node', REDHEN_ORG_GROUP_FIELD, $type);
        if ($instance) {
          field_delete_instance($instance, FALSE);
          field_purge_batch(10);
          drupal_set_message(t('Field %label has been deleted from the %type content type.',
            array('%label' => $instance['label'], '%type' => $type)));
        }
      }
    }
  }
}
