<?php

define('REDHEN_ORG_GROUP_FIELD', 'field_redhen_org_group');

/**
 * Implements hook_form_FORM_ID_alter().
 */
function redhen_org_group_form_redhen_org_type_form_alter(&$form, &$form_state) {
  // add group specific settings
  $redhen_org_type = $form['#redhen_org_type'];
  $form['data']['group'] = array(
    '#type' => 'checkbox',
    '#title' => 'Groupify',
    '#default_value' => isset($redhen_org_type->group) ? $redhen_org_type->group : NULL
  );
  $form['data']['group_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Group settings'),
    '#states' => array(
      'visible' => array(
        ':input[name="data[group]"]' => array('checked' => TRUE),
      ),
    )
  );
  $form['data']['group_settings']['private'] = array(
    '#type' => 'checkbox',
    '#title' => t('Private'),
    '#default_value' => isset($redhen_org_type->group_settings['private']) ? $redhen_org_type->group_settings['private'] : NULL
  );

  $form['data']['group_settings']['content_types'] = array(
    '#type' => 'select',
    '#title' => t('Content types'),
    '#description' => t('Select which content types can be posted into this group.'),
    '#options' => node_type_get_names(),
    '#multiple' => TRUE,
    '#default_value' => isset($redhen_org_type->group_settings['content_types']) ? $redhen_org_type->group_settings['content_types'] : array()
  );

  $form['#submit'][] = 'redhen_org_group_redhen_org_type_form_submit';
}

/**
 * Submit handler for redhen_org_type_form().
 *ddnngyhh
 * @param $form
 * @param $form_state
 */
function redhen_org_group_redhen_org_type_form_submit($form, &$form_state) {
  // create an instance of our audience field if it doesn't already exist
  // @todo: handle the unselection of an entity type
  $content_types = $form_state['values']['data']['group_settings']['content_types'];
  foreach ($content_types as $type) {
    $instance = field_read_instance('node', REDHEN_ORG_GROUP_FIELD, $type);

    // create the field
    if (!$instance) {
      $instance = array(
        'field_name' => REDHEN_ORG_GROUP_FIELD,
        'entity_type' => 'node',
        'bundle' => $type,
        'label' => t('Group'),
        'widget' => array(
          'module' => 'options',
          'settings' => array(),
          'type' => 'options_select',
        ),
      );

      field_create_instance($instance);
    }
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function redhen_org_group_ctools_plugin_directory($module, $plugin) {
  if ($module == 'entityreference') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_redhen_org_type_delete()
 *
 * @param RedhenOrgType $redhen_org_type
 */
function redhen_org_group_redhen_org_type_delete(RedhenOrgType $redhen_org_type) {
  // delete redhen group field
  // @todo: make sure entity type in question isn't being used by other groups
  if (isset($redhen_org_type->group_settings['content_types'])) {
    foreach ($redhen_org_type->group_settings['content_types'] as $type) {
      $instance = field_read_instance('node', REDHEN_ORG_GROUP_FIELD, $type);
      if ($instance) {
        field_delete_instance($instance, FALSE);
        drupal_set_message(t('Deleted the @group_field associated with '));
      }
    }
  }
}
