<?php

define('REDHEN_ORG_GROUP_FIELD', 'field_redhen_org_group');

/**
 * Implements hook_form_FORM_ID_alter().
 */
function redhen_org_group_form_redhen_org_type_form_alter(&$form, &$form_state) {
  // add group specific settings
  $redhen_org_type = $form['#redhen_org_type'];
  $form['data']['group'] = array(
    '#type' => 'checkbox',
    '#title' => 'Groupify',
    '#default_value' => isset($redhen_org_type->group) ? $redhen_org_type->group : NULL
  );
  $form['data']['group_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Group settings'),
    '#states' => array(
      'visible' => array(
        ':input[name="data[group]"]' => array('checked' => TRUE),
      ),
    )
  );
  $form['data']['group_settings']['private'] = array(
    '#type' => 'checkbox',
    '#title' => t('Private'),
    '#default_value' => isset($redhen_org_type->group_settings['private']) ? $redhen_org_type->group_settings['private'] : NULL
  );

  $entities = entity_get_info();
  $options = array();
  foreach ($entities as $entity_name => $entity) {
    if ($entity['fieldable']) {
      foreach ($entity['bundles'] as $name => $bundle) {
        $options[$entity['label']][$entity_name . ':' . $name] = $bundle['label'];
      }
    }
  }
  $form['data']['group_settings']['entity_types'] = array(
    '#type' => 'select',
    '#title' => t('Entity types'),
    '#description' => t('Select which entity types can be posted into this group.'),
    '#options' => $options,
    '#multiple' => TRUE,
    '#default_value' => isset($redhen_org_type->group_settings['entity_types']) ? $redhen_org_type->group_settings['entity_types'] : array()
  );

  $form['#submit'][] = 'redhen_org_group_redhen_org_type_form_submit';
}

/**
 * Submit handler for redhen_org_type_form().
 *
 * @param $form
 * @param $form_state
 */
function redhen_org_group_redhen_org_type_form_submit($form, &$form_state) {
  // create an instance of our audience field if it doesn't already exist
  $entity_types = $form_state['values']['data']['group_settings']['entity_types'];
  foreach ($entity_types as $type) {
    list($entity_type, $bundle) = explode(':', $type);
    $instance = field_read_instance($entity_type, REDHEN_ORG_GROUP_FIELD, $bundle);

    // create the field
    if (!$instance) {
      $instance = array(
        'field_name' => REDHEN_ORG_GROUP_FIELD,
        'entity_type' => $entity_type,
        'bundle' => $bundle,
        'label' => t('Group'),
        'widget' => array(
          'module' => 'options',
          'settings' => array(),
          'type' => 'options_select',
        ),
      );

      field_create_instance($instance);
    }
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function redhen_org_group_ctools_plugin_directory($module, $plugin) {
  if ($module == 'entityreference') {
    return 'plugins/' . $plugin;
  }
}
